CREATE TABLE servicepro_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating INTEGER NOT NULL,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    service_id INTEGER REFERENCES servicepro_services(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER REFERENCES servicepro_users(id) ON DELETE CASCADE NOT NULL
);